### ISSUE TITLE
Installatie op Windows is onhandig

### ISSUE THREAD

**Issue by arp242** [Carpetsmoker/download-npo#1]
Was Bitbucket issue 9:
- Ik krijg cx_freeze niet meer aan de praat op een nieuwe VM - vage errors.
- PyInstaller geprobeerd: ook vage errors

Er zijn nu handmatige installatie instructies, wat op zich goed werkt, maar een stand-alone .exe zoals voorheen zou wel beter zijn.

**Comment by jeroenl** [comment]
@Carpetsmoker Is het inmiddels mogelijk om de installer bij te werken? Of is er een andere manier om de nieuwste download-npo op windows te installeren?

**Comment by arp242** [comment]
Je kan `pip` gebruiken op Windows @jeroenl, maar je moet dan wel Python handmatig installeren vanaf python.org. Iets meer moeite.

Dit weer werkend krijgen is eerlijk gezegd geen prioriteit op het moment. Ik denk dat >50% van alle tijd in download-npo in de Windows installer zit – iets wat ik zelf nooit gebruik. Rommelen met VMs e.d. is saai en vermoeiend werk :-/

Patches zijn welkom voor het geval dat iemand anders zin/tijd heeft om dit te maken/onderhouden :-)

Tot nu toe heeft de oude 2.1 versie altijd goed gewerkt, maar nu dus niet meer :-/ Ik zal binnenkort wel de README e.d. updaten met actuele installatieinstructies (m.b.v `pip`).

**Comment by jeroenl** [comment]
Ja, vandaar dat ik het vraag. Instructies zijn welkom. Het is mij nog niet gelukt met pip.

(Is cx_Freeze nodig voor gewone installatie? Zo ja: de opties zijn zo te zien iets aangepast voor cx_Freeze 5.0)

**Comment by arp242** [comment]
> Is cx_Freeze nodig voor gewone installatie

Nee, je hebt verder niks nodig behalve Python zelf (cx_freeze is alleen nodig om een stand-alone .exe te maken).

> Het is mij nog niet gelukt met pip.

Hm, krijg je een foutmelding? Of wat gaat er precies fout?

**Comment by jeroenl** [comment]
Als ik verder helemaal niets doe:

```
Collecting download-npo
  Using cached download-npo-2.4.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "D:\Users\Jeroen\AppData\Local\Temp\pip-build-wgre8fgo\download-npo\setup.py", line 11, in <module>
        from cx_Freeze import setup, Executable
    ImportError: No module named 'cx_Freeze'
```

**Comment by arp242** [comment]
Ah, dat cx_freeze spul enzo zat er nog in. Ik heb dat weggehaald, en nu als weer twee avonden aan het stoeien ermee, ik krijg het zo niet aan de praat met `pip` op Windows.

Wel de instructies geupdate en `download-npo-gui` hernoemd naar `download-npo-gui.pyw` zodat dubbelklikken goed werkt op Windows.

Iets meer moeite dan voorheen, maar op zich nog wel te doen.

**Comment by jeroenl** [comment]
Nu krijg ik:
```
Collecting download-npo
  Downloading download-npo-2.5.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "D:\Users\Jeroen\AppData\Local\Temp\pip-build-_ljfnpll\download-npo\setup.py", line 16, in <module>
        shutil.copyfile('download-npo-gui.pyw', 'build/download-npo-gui')
      File "C:\Anaconda\lib\shutil.py", line 114, in copyfile
        with open(src, 'rb') as fsrc:
    FileNotFoundError: [Errno 2] No such file or directory: 'download-npo-gui.pyw'
```

Ik heb ook geen download-npo-gui.pyw script. Wellicht moet de bestandsnaam daarvan ook in setup.py aangepast worden, om te zorgen dat het in het archive meegenomen wordt?

**Comment by arp242** [comment]
`setup.py` werkt niet op Windows. Je zal het handmatig moeten uitpakken en `download-npo-gui.pyw` moeten uitvoeren (dubbelklikken als je Python geïnstalleerd hebt zou moeten werken).

Ik weet zo niet waarom je die error krijgt. Moet ik even naar kijken; maar dat staat er verder los van.

**Comment by jeroenl** [comment]
Andere packages werken gewoon met pip / setup.py, geloof niet dat dat anders is bij Windows. Ik moest alleen het '/usr/share/icons/hicolor/scalable/apps' pad veranderen (en mutagen installeren), maar verder kon ik via setup.py het package installeren. Bedankt!

**Comment by arp242** [comment]
AppVeyor bouwt nu Windows installers: https://ci.appveyor.com/project/Carpetsmoker/download-npo/branch/master

De installer is bij de versie en dan "Artifacts". Je moet nog wel steeds handmatig Python installeren, dus het is nog niet 100% automatisch zoals voorheen.
Moet alleen nog even testen of deze installers ook echt werken...
