### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by djkwee20** [Carpetsmoker/download-npo#13]
Ubuntu 16.04 - download-npo version 2.7 , python 2.7, python3

Python 2.7
$ ./download-npo https://www.npo.nl/nooit-meer-slapen/23-03-2017/RBX_VPRO_5273361
Traceback (most recent call last):
  File "./download-npo", line 6, in <module>
    download_npo.cli.main()
  File "/media/wd500/uitzending.gemist.download/download-npo-2.7/download_npo/cli.py", line 324, in main
    options['metaonly'], options['getsubs'], options['quality'])
  File "/media/wd500/uitzending.gemist.download/download-npo-2.7/download_npo/cli.py", line 183, in download
    videourl, player_id, ext = site.find_video(vid, quality)
  File "/media/wd500/uitzending.gemist.download/download-npo-2.7/download_npo/sites.py", line 231, in find_video
    stream = self.get_json(stream['url'])
  File "/media/wd500/uitzending.gemist.download/download-npo-2.7/download_npo/sites.py", line 89, in get_json
    data = json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

-----
Python 3
$ python3 download-npo https://www.npo.nl/nooit-meer-slapen/23-03-2017/RBX_VPRO_5273361
Traceback (most recent call last):
  File "download-npo", line 6, in <module>
    download_npo.cli.main()
  File "/media/wd500/uitzending.gemist.download/download-npo-2.7/download_npo/cli.py", line 324, in main
    options['metaonly'], options['getsubs'], options['quality'])
  File "/media/wd500/uitzending.gemist.download/download-npo-2.7/download_npo/cli.py", line 183, in download
    videourl, player_id, ext = site.find_video(vid, quality)
  File "/media/wd500/uitzending.gemist.download/download-npo-2.7/download_npo/sites.py", line 231, in find_video
    stream = self.get_json(stream['url'])
  File "/media/wd500/uitzending.gemist.download/download-npo-2.7/download_npo/sites.py", line 87, in get_json
    data = re.sub(r'^[\w\d\?]+\(', r'', self.get_page(url))
  File "/media/wd500/uitzending.gemist.download/download-npo-2.7/download_npo/sites.py", line 82, in get_page
    data = data.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

Graag uw reactie

**Comment by arp242** [comment]
Ziet eruit als hetzelfde probleem als: https://github.com/Carpetsmoker/download-npo/issues/10

Output in dit geval:

```
{'items': [[{'contentType': 'audio',
             'format': 'mp3',
             'label': '',
             'url': 'http://radiobox2.omroep.nl/broadcaststream/file/490525.mp3'}]],
 'limited': False,
 'site': None}
```

De vraag is alleen of dit voor alle audio bestanden geld, of alleen voor sommige.

Zal later verder kijken – moet nu weg :-)

**Comment by arp242** [comment]
Oudere radio uitzending die in het verleden (Maart 2016) ooit gewerkt heeft, heeft nu ook hetzelfde probleem:
http://www.npo.nl/bert-keizer-leven-met-de-dood/21-02-2016/RBX_NTR_709318

Dus de site is in de tussentijd veranderd, of ik heb iets kapot gemaakt :-)

**Comment by djkwee20** [comment]
Beste Martin,
Dezelfde fout treedt ook op bij andere URL. Ze zijn .mp3 bestanden

	$ ./download-npo https://www.npo.nl/voor-de-dag/23-03-2017/RBX_KN_4919592

	Traceback (most recent call last):  File "./download-npo", line 6, in <module>    download_npo.cli.main()  File "/media/wd500/uitzending.gemist.download/download-npo-2.7/download_npo/cli.py", line 324, in main    options['metaonly'], options['getsubs'], options['quality'])  File "/media/wd500/uitzending.gemist.download/download-npo-2.7/download_npo/cli.py", line 183, in download    videourl, player_id, ext = site.find_video(vid, quality)  File "/media/wd500/uitzending.gemist.download/download-npo-2.7/download_npo/sites.py", line 231, in find_video    stream = self.get_json(stream['url'])  File "/media/wd500/uitzending.gemist.download/download-npo-2.7/download_npo/sites.py", line 89, in get_json    data = json.loads(data)  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads    return _default_decoder.decode(s)  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode    obj, end = self.raw_decode(s, idx=_w(s, 0).end())  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode    raise ValueError("No JSON object could be decoded")ValueError: No JSON object could be decoded

Bedankt voor de moeite.
Gr Djien

**Comment by djkwee20** [comment]
Als ik Online Programma Gemist Downloader gebruikt, downloaden is OK.
  
|  
|   |  
Online Programma Gemist Downloader
 Plak, klik & download! Downloadgemist.nl is de snelste manier om video's te downloaden van NPO Uitzendin...  |  |

  |

 
Maar ik prefereer jouw download-npo.
Gr, Djien

**Comment by djkwee20** [comment]
Geen problemen bij downloaden mp4 bestanden. Alleen downloaden mp3 bestanden.

**Comment by arp242** [comment]
Lijkt inderdaad zo te zijn voor alle radio-uitzendingen.

Zou in versie 2.7.1 gefixed moeten zijn. Dank voor het melden.
