### ISSUE TITLE
 BUG: Unhandled error in plugin npo_watchlist: 'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by daurigi** [Carpetsmoker/download-npo#15]
latest version of flexget and download-npo installed.

config.yml
tasks:
  tv-journaal:
    npo_watchlist:
      email: xxx
      password: yyy 
      remove_accepted: yes
      max_episode_age_days: 7
    accept_all: yes
    exec:
      fail_entries: yes
      auto_escape: yes
      on_output:
        for_accepted:
          - /usr/local/bin/download-npo -o "/var/storage/queue/tvshows/NPO/{{series_name_plain}}" -f "{serie_titel} - {datum} {aflevering_titel} ({episode_id})" -t {{url}}

2017-07-05 20:31 CRITICAL task          tv-journaal     BUG: Unhandled error in plugin npo_watchlist: 'NoneType' object has no attribute 'find'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 486, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/input/npo_watchlist.py", line 326, in on_task_input
    entries += self._get_favorites_entries(task, config)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/input/npo_watchlist.py", line 318, in _get_favorites_entries
    series_info = self._get_series_info(task, config, series_name, url)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/input/npo_watchlist.py", line 180, in _get_series_info
    series_info['npo_url'] = tvseries.find('a', itemprop='url')['href']
AttributeError: 'NoneType' object has no attribute 'find'

Something changed on the NPO site?

**Comment by arp242** [comment]
Lijkt een probleem in Flexget? Ik onderhoud deze plugin zelf niet.

En ja, op maandag hebben ze een nieuwe site live gedaan wat het eea. veranderde.

**Comment by daurigi** [comment]
Weet je of er aan een nieuwe versie wordt gewerkt die de nieuwe site layout kan lezen?

**Comment by mfonville** [comment]
@daurigi ik zal binnenkort de flexget plugin updaten wanneer ik tijd heb, nog geen ETA ivm een drukke agenda :-/

**Comment by arp242** [comment]
Ik onderhoud de flexget plugin zelf niet, dus is in princiepe geen bug in download-npo. Je kan op de Flexget issue tracker een bug melden, en hopelijk dat men daar meer tijd heeft om er naar te kijken :-)
