### ISSUE TITLE
UnicodeEncodeError met Python 2

### ISSUE THREAD

**Issue by arp242** [Carpetsmoker/download-npo#4]
```
[/data/code/download-npo](list)% python2 download-npo http://www.npo.nl/gouden-jaren-indonesie/26-01-2017/POW_03414349
Traceback (most recent call last):
  File "download-npo", line 308, in <module>
    options['metaonly'], options['getsubs'], options['quality'])
  File "download-npo", line 182, in Download
    _options['replacespace'], _options['overwrite'])
  File "/data/code/download-npo/download_npo/__init__.py", line 146, in MakeFilename
    outfile = u'%s/%s' % (outdir.decode('utf-8'), filename.decode('utf-8'))
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xeb' in position 21: ordinal not in range(128)
Exit 1
```

**Comment by arp242** [comment]
Fixed in versie 2.5.2
