### ISSUE TITLE
Ondertitels ophalen werkt niet

### ISSUE THREAD

**Issue by mfonville** [Carpetsmoker/download-npo#6]
Sinds de laatste NPO.nl update van donderdag werkt de optie om ondertitels te downloaden niet meer :-/

een voorbeeldje van output
```
download-npo -t http://www.npo.nl/keuringsdienst-van-waarde/26-01-2017/KN_1687595
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/download_npo/sites.py", line 58, in OpenUrl
    return urllib2.urlopen(req)
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 410: Gone

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/download-npo", line 308, in <module>
    options['metaonly'], options['getsubs'], options['quality'])
  File "/usr/bin/download-npo", line 220, in Download
    fp.write(site.Subs(playerId).read())
  File "/usr/lib/python3/dist-packages/download_npo/sites.py", line 299, in Subs
    return self.OpenUrl('http://e.omroep.nl/tt888/%s' % playerId)
  File "/usr/lib/python3/dist-packages/download_npo/sites.py", line 61, in OpenUrl
    'De URL {} is niet gevonden (404 error)'.format(url))
download_npo.DownloadNpoError: De URL http://e.omroep.nl/tt888/KN_1687595 is niet gevonden (404 error)
```

**Comment by jhoek** [comment]
De subs wonen tegenwoordig hier, zo te zien: http://tt888.omroep.nl/tt888/%s.

**Comment by arp242** [comment]
Fixed in #7
